kind: pipeline
type: docker
name: kube-alert

platform:
  os: linux
  arch: amd64

steps:
  - name: 编译Build
    image: golang:1.13.4
    commands:
      - go test
      - go build -o kube-alert
    volumes:
      - name: gopath
        path: /go
    environment:
      GOPROXY: https://goproxy.cn,direct
      GOSUMDB: sum.golang.google.cn
      GOPRIVATE: gitcodecloud.lenovo.com.cn
      CGO_ENABLED: "0"

  - name: 构建镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.cn-beijing.aliyuncs.com/octopus-tool/kube-alert
      registry: registry.cn-beijing.aliyuncs.com
      tags: ${DRONE_BUILD_NUMBER}

  - name: Kubernetes 部署
    image: guoxudongdocker/kubectl:v1.14.1
    volumes:
      - name: kube
        path: /root/.kube
    commands:
      - sed -i "s/#Tag/${DRONE_BUILD_NUMBER}/g" job.yml
      - kubectl apply -f job.yml
    when:
      status: [failure, success]

  - name: 钉钉通知
    image: guoxudongdocker/drone-dingtalk
    settings:
      token:
        from_secret: dingding
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]

volumes:
  - name: kube
    host:
      path: /root/drone/kube
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: gopath
    host:
      path: /root/drone/gopath

trigger:
  branch:
    - master




